// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartCommunity.Api.Data;

#nullable disable

namespace SmartCommunity.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261006123831_Week5GoogleMapsLocation")]
    partial class Week5GoogleMapsLocation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartCommunity.Api.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SmartCommunity.Api.Models.CommunityReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<Guid>("CurrentStatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_status_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("GooglePlaceId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("google_place_id");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("location");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("ReferenceNo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("reference_no");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("resident_id");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceNo")
                        .IsUnique();

                    b.HasIndex("CategoryId", "SubmittedAt");

                    b.HasIndex("CurrentStatusId", "SubmittedAt");

                    b.HasIndex("ResidentId", "SubmittedAt");

                    b.ToTable("reports", null, t =>
                        {
                            t.HasCheckConstraint("CK_reports_coordinate_pair", "(latitude IS NULL AND longitude IS NULL) OR (latitude IS NOT NULL AND longitude IS NOT NULL)");

                            t.HasCheckConstraint("CK_reports_latitude", "latitude IS NULL OR (latitude >= -90 AND latitude <= 90)");

                            t.HasCheckConstraint("CK_reports_longitude", "longitude IS NULL OR (longitude >= -180 AND longitude <= 180)");
                        });
                });

            modelBuilder.Entity("SmartCommunity.Api.Models.IssueCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3f8d8599-7bbd-4f05-a915-7196b552f001"),
                            Description = "Potholes, cracks and access hazards",
                            IsActive = true,
                            Name = "Roads & footpaths",
                            Slug = "roads-footpaths",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = new Guid("3f8d8599-7bbd-4f05-a915-7196b552f002"),
                            Description = "Faulty or damaged public lighting",
                            IsActive = true,
                            Name = "Street lighting",
                            Slug = "street-lighting",
                            SortOrder = 20
                        },
                        new
                        {
                            Id = new Guid("3f8d8599-7bbd-4f05-a915-7196b552f003"),
                            Description = "Illegal dumping and overflowing bins",
                            IsActive = true,
                            Name = "Waste & dumping",
                            Slug = "waste-dumping",
                            SortOrder = 30
                        },
                        new
                        {
                            Id = new Guid("3f8d8599-7bbd-4f05-a915-7196b552f004"),
                            Description = "Playgrounds, signs and shared spaces",
                            IsActive = true,
                            Name = "Parks & facilities",
                            Slug = "parks-facilities",
                            SortOrder = 40
                        });
                });

            modelBuilder.Entity("SmartCommunity.Api.Models.ReportStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("report_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7c20c2c3-45f8-4d9c-8525-593a1841a001"),
                            Code = "SUBMITTED",
                            Name = "Submitted",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = new Guid("7c20c2c3-45f8-4d9c-8525-593a1841a002"),
                            Code = "UNDER_REVIEW",
                            Name = "Under review",
                            SortOrder = 20
                        },
                        new
                        {
                            Id = new Guid("7c20c2c3-45f8-4d9c-8525-593a1841a003"),
                            Code = "ASSIGNED",
                            Name = "Assigned",
                            SortOrder = 30
                        },
                        new
                        {
                            Id = new Guid("7c20c2c3-45f8-4d9c-8525-593a1841a004"),
                            Code = "IN_PROGRESS",
                            Name = "In progress",
                            SortOrder = 40
                        },
                        new
                        {
                            Id = new Guid("7c20c2c3-45f8-4d9c-8525-593a1841a005"),
                            Code = "RESOLVED",
                            Name = "Resolved",
                            SortOrder = 50
                        },
                        new
                        {
                            Id = new Guid("7c20c2c3-45f8-4d9c-8525-593a1841a006"),
                            Code = "CLOSED",
                            Name = "Closed",
                            SortOrder = 60
                        });
                });

            modelBuilder.Entity("SmartCommunity.Api.Models.StatusHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by_user_id");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_id");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("status_id");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("StatusId");

                    b.HasIndex("ReportId", "ChangedAt");

                    b.ToTable("status_history", (string)null);
                });

            modelBuilder.Entity("SmartCommunity.Api.Models.CommunityReport", b =>
                {
                    b.HasOne("SmartCommunity.Api.Models.IssueCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartCommunity.Api.Models.ReportStatus", "CurrentStatus")
                        .WithMany()
                        .HasForeignKey("CurrentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartCommunity.Api.Models.AppUser", "Resident")
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("CurrentStatus");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("SmartCommunity.Api.Models.StatusHistoryEntry", b =>
                {
                    b.HasOne("SmartCommunity.Api.Models.AppUser", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartCommunity.Api.Models.CommunityReport", "Report")
                        .WithMany()
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartCommunity.Api.Models.ReportStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("Report");

                    b.Navigation("Status");
                });
#pragma warning restore 612, 618
        }
    }
}
